# Generated by Django 5.2 on 2025-04-15 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosed_with',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='discharged_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(default='ill'),
            preserve_default=False,
        ),
    ]
