# Generated by Django 5.0.1 on 2025-05-04 13:13

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_admitted_on_patient_date_admitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
