# Generated by Django 5.0.1 on 2025-05-04 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patient_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
